version: '{build}'
image: Visual Studio 2017

configuration:
  - Release

before_build:
  - mkdir build && cd build
  - cmake ../ -G "Visual Studio 15 2017"

build_script:
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --config %CONFIGURATION% --target package

on_failure:
  - type Testing\Temporary\LastTest.log

artifacts:
  - path: rcon-*-windows.zip
    name: RCON executable

deploy:
  description: '<Put release description here>'
  provider: GitHub
  auth_token:
    secure: xhaxB+TKUkVbIdmjPxca6T72wOV18gD5wfv0M5dbnrqbzDvcQTGwTuYHKzLn5hal
  artifact: /rcon-.*-windows\.zip/
  draft: true
  on:
    appveyor_repo_tag: true
